# Generated by Django 4.1.2 on 2022-11-04 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform0', models.CharField(blank=True, max_length=100)),
                ('inform1', models.CharField(blank=True, max_length=100)),
                ('inform2', models.CharField(blank=True, max_length=100)),
                ('inform3', models.CharField(blank=True, max_length=100)),
                ('inform4', models.CharField(blank=True, max_length=100)),
                ('inform5', models.CharField(blank=True, max_length=100)),
                ('inform6', models.CharField(blank=True, max_length=100)),
                ('inform7', models.CharField(blank=True, max_length=100)),
                ('inform8', models.CharField(blank=True, max_length=100)),
                ('inform9', models.CharField(blank=True, max_length=100)),
                ('inform10', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform1', models.CharField(blank=True, max_length=100)),
                ('inform2', models.CharField(blank=True, max_length=100)),
                ('inform3', models.CharField(blank=True, max_length=100)),
                ('inform4', models.CharField(blank=True, max_length=100)),
                ('inform5', models.CharField(blank=True, max_length=100)),
                ('inform6', models.CharField(blank=True, max_length=100)),
                ('inform7', models.CharField(blank=True, max_length=100)),
                ('inform8', models.CharField(blank=True, max_length=100)),
                ('inform9', models.CharField(blank=True, max_length=100)),
                ('inform10', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
